### ISSUE TITLE
Add project(s)/domain(s) for each mentor where they can help

### ISSUE THREAD

**Issue by tahirwaseer** [lenadroid/awesome-oss-mentors#15]
Some details about mentors like in which areas they are working, where they will be more happy to help e.g OSS project name or maybe specific programming languages. It would help find the right person for help more easily.

**Comment by lenadroid** [comment]
Thanks @tahirwaseer! Because I personally don't know each mentor, I just took the content of the tweet they replied with, when they volunteered. A lot of them weren't specific. A lot of them indicated multiple technologies and areas, which I put in the focus field.

**Comment by tahirwaseer** [comment]
That is helpful and I am also thinking about some alternate way to arrange this list and making more accessible. Maybe would get some time on the weekend, would let you know about that as well.
