### ISSUE TITLE
I will be watching this! 

### ISSUE THREAD

**Issue by ghost** [lenadroid/awesome-oss-mentors#21]
I am mega grateful for this, there are some names I will ask to be removed if they appear.

**Comment by ghost** [comment]
Will be submitting a PR for @stakx ;)

**Comment by stakx** [comment]
>Will be submitting a PR for @stakx ;)

Given that this thing started on Twitter, did you mean https://twitter.com/stakx or me? :)

(This is actually quite a nice project. I probably wouldn't mind at all being listed here... given the project's name that would seem like quite an honour. Thanks for thinking of me! :-)

**Comment by ghost** [comment]
Aww sorry mate, I meant the twitter guy! Lol

**Comment by ghost** [comment]
Of course it is you! ;)

**Comment by fir3pho3nixx** [comment]
Common yaakov, don't want to join?
