### ISSUE TITLE
What if they are not publicly identifiable via Twitter?

### ISSUE THREAD

**Issue by ghost** [lenadroid/awesome-oss-mentors#22]
Awesome campaign. What if they care about privacy and are different people on github and twitter?

@github != @twitter

**Comment by lenadroid** [comment]
True! That's why I named the column "Twitter/Github", if a person prefers to just link the Github. 
Current list of people has mostly Twitter everywhere because they replied/volunteered on Twitter :) 

or did you mean something else?

**Comment by Cynede** [comment]
how will they communicate on github

**Comment by ankibalyan** [comment]
Email or any other social link, like gitter, discord, spectrum, Web IRC. etc. ?

**Comment by ghost** [comment]
His profile only has links to Stackoverflow and Github. 
He mainly communicates through questions and issues :)

** Edited **

I am pretty sure he will answer just about any question.

**Comment by lenadroid** [comment]
Thanks everyone, good points. I will update the text and emphasize that it's important to be reachable, etc. When I do it, I'll post a "ping" here, and if y'all think it's good enough, we'll close the issue then.

**Comment by lenadroid** [comment]
So, I updated the text to include "be reachable" and there's now "contact" column too. Didn't populate it for existing mentors, cuz I don't have that info for them. But the new ones should be better. Is that ok?

**Comment by ghost** [comment]
Maybe, just maybe, we have conflicting things going on. 

This person cares about privacy but if you ever find yourself on the CastleProject or Moq on github(even Stackoverflow) he will be more than happy to answer questions and guide one(especially n00bs like me). 

Could we forgo the "contact" column being mandatory for this OSS mentor. This person knows heaps about stuff and things, I can also appreciate why he likes his privacy in this day and age.

**Comment by ghost** [comment]
Scratch that, closing! Thanks all :)
