### ISSUE TITLE
Need help with contribution to Debian

### ISSUE THREAD

**Issue by jnoni** [lenadroid/awesome-oss-mentors#46]
Hi there.

[This](https://www.outreachy.org/2018-may-august/communities/debian/) is the project to which I will be applying to for the summer internship. Can anyone please help me with my first contribution, if you've got some knowledge/experience with Debian packaging skills? Or if not you, then maybe a friend of yours who might have missed this post?

My email ID: rupal15081@iiitd.ac.in

**Comment by jnoni** [comment]
@lenadroid 
@ofek 
Can I get some pointers?

**Comment by lenadroid** [comment]
I'm on it! Let me find some friendly mentors for you.

**Comment by ofek** [comment]
I'm sorry, what would you like help with?

**Comment by jnoni** [comment]
@ofek

The project within Debian that I want to apply to is "Quality assurance for biological applications inside Debian". Mainly because I have a background and interest in Computational Biology and luckily I could resonate with this project due to the CB part. The other component of it (and the most important and major one, on which all implementations will be based) is Debian packaging.--> this is where I need help mainly.

I have started looking at some resources on Google for it to get a gist of it (to get acquainted with the basic terms), but I still feel that to actual get into coding it up, I'll need someone's mentoring.

Well, I think this hurdle and hesitation is partly due to my first encounter with Open source. And to not make it feel anymore alien to me, I thought to ask here for help.

**Comment by lenadroid** [comment]
Maybe @0xaf1f, @aburch, @algernon, @ana, @aviau, @charles-plessy, @ebourg, @eddelbuettel, @ghedo, @jamessan, @matthieucan, @Mezzle, @milan-kupcevic, @nomadium, @nthykier, @paultag, @rhertzog, @samueloph, @spwhitton, @venthur, @warsaw, @yarikoptic, @zacchiro know someone who could help?

**Comment by 0xaf1f** [comment]
@Rupal-IIITD, the project you're talking about is from the [Debian Med team](https://www.debian.org/devel/debian-med/). We also have a little [packaging mentorship program](https://wiki.debian.org/DebianMed/MoM). If you contact debian-med@lists.debian.org, you can get some more information and get started.

**Comment by lenadroid** [comment]
Hey @Rupal-IIITD, bureado [at] debian [dot] org is also happy to help! Let me know if you have any questions.

**Comment by 0xaf1f** [comment]
@Rupal-IIITD, I read your comment more carefully, and I don't believe Andreas Tille (the mentor for the project) intended Debian packaging knowledge as a prerequisite for this project. It is listed as "nice to have" there after all. Again, if you contact the Debian Med mailing list, you can ask for clarification.
